name: "build process"
run-name: "Build process"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Remove unwanted stuff
        uses: gbraad-actions/remove-unwanted@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential flex bison dwarves libssl-dev libelf-dev cpio qemu-utils

      - name: Checkout WSL2 kernel source
        uses: actions/checkout@v4
        with:
          repository: 'microsoft/WSL2-Linux-Kernel'
          fetch-depth: 2

      - name: Build prep
        run: |
          cp Microsoft/config-wsl .config
          make oldconfig
          scripts/config --disable SYSTEM_REVOCATION_KEYS
      
      - name: Run kernel build
        run: |
          make -j $(nproc)

      - name: Run modules build
        run: |
          make INSTALL_MOD_PATH="$PWD/modules" modules_install

      - name: Create modules.vhdx
        run: |
          sudo ./Microsoft/scripts/gen_modules_vhdx.sh "$PWD/modules" $(make -s kernelrelease) modules.vhdx

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wsl2-kernel
          path: arch/x86/boot/bzImage
          retention-days: 7

      - name: Upload modules artifact 
        uses: actions/upload-artifact@v4
        with:
          name: wsl2-modules
          path: modules.vhdx
          retention-days: 7

  
